# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Portfolio to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: joatmon08/tech-portfolio
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and static website
      run: |
        cd website
        yarn install
        yarn build
        touch .nojekyll
    - name: Push to gh-pages
      run: |
        cd website
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        GIT_USER=joatmon08 GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} CURRENT_BRANCH=master npm run publish-gh-pages